# Site settings
title: DataBR
email: contato@databr.io
description: >
  DataBR é um conjunto de <abbr title="em português: Interface de Programação de Aplicações">API</abbr> para ajudar desenvolvedores, jornalistas, analistas e quem mais tiver interesse em trabalhar dados do governo brasileiro. Acreditamos que com nosso esforço na coleta e analise de dados, possibilitando a criação de aplicativos, jogos e visualizações, estamos ajudando para um Brasil melhor.
baseurl: ""
url: "http://databr.io"

markdown: kramdown

twitter: databr_api
