# Site settings
title: DataBR
email: contato@databr.io
description: >
  DataBR é um conjunto de <abbr title="em português: Interface de Programação de Aplicações">API's</abbr> que possibilita desenvolvedores, jornalistas, analistas e demais interessados, trabalhar com dados governamentais brasileiros. Acreditamos que este esforço em dispôr os dados de maneira aberta, possibilita a criação de inovadoras soluções para um país melhor, criando mais engajamento entre a população e os representantes do governo.
baseurl: ""
url: "http://databr.io"

markdown: kramdown

sources:
  -
    name: "Senado Federal"
    image: "images/senado.jpg"
    link: "http://senado.gov.br"
  -
    name: "Câmara dos Deputados"
    image: "images/camaradodeputados.jpg"
    link: "http://www2.camara.leg.br"
  -
    name: "Transparência Brasil"
    image: "images/transparenciabrasil.png"
    link: "http://transparencia.org.br"
  -
    name: "CPTM"
    image: "images/cptm.png"
    link: "http://cptm.sp.gov.br"
  -
    name: "Metro (SP)"
    image: "images/metrosp.gif"
    link: "http://www.metro.sp.gov.br"


partners:
  -
    name: "StatusPage.io"
    image: "images/statuspage.png"
    link: "http://StatusPage.io"
  -
    name: "Transparência SJC"
    image: "images/transparenciasjc.jpg"
    link: "http://transparenciasjc.github.io/"

cases:
  -
    name: "Exemplo: Situação Linhas do Metrô/CPTM"
    link: "/examples/status-metro-cptm"
