# Site settings
title: DataBR
email: contato@databr.io
description: >
  DataBR é um conjunto de <abbr title="em português: Interface de Programação de Aplicações">API</abbr> para ajudar desenvolvedores, jornalistas, analistas e quem mais tiver interesse em trabalhar dados do governo brasileiro. Acreditamos que com nosso esforço na coleta e analise de dados, possibilitando a criação de aplicativos, jogos e visualizações, estamos ajudando para um Brasil melhor.
baseurl: ""
url: "http://databr.io"

markdown: kramdown

sources:
  -
    name: "Senado Federal"
    image: "images/senado.jpg"
    link: "http://senado.gov.br"
  -
    name: "Câmara dos Deputados"
    image: "images/camaradodeputados.jpg"
    link: "http://www2.camara.leg.br"
  -
    name: "Transparência Brasil"
    image: "images/transparenciabrasil.png"
    link: "http://transparencia.org.br"


partners:
  -
    name: "StatusPage.io"
    image: "images/statuspage.png"
    link: "http://StatusPage.io"
  -
    name: "Transparência SJC"
    image: "images/transparenciasjc.jpg"
    link: "http://transparenciasjc.github.io/"

